apiVersion: v1
kind: Service
metadata:
  name: triton-credit-risk
  labels:
    app.kubernetes.io/name: triton-credit-risk
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: triton-credit-risk
    app.kubernetes.io/component: gpu-inference
  ports:
    - name: http
      port: 8000
      targetPort: http
    - name: grpc
      port: 8001
      targetPort: grpc
    - name: metrics
      port: 8002
      targetPort: metrics
