apiVersion: v1
kind: Namespace
metadata:
  name: regulated-ml-preprod
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    environment: preprod
