apiVersion: v1
kind: ResourceQuota
metadata:
  name: regulated-ml-budget
spec:
  hard:
    requests.cpu: "32"
    requests.memory: 96Gi
    limits.cpu: "64"
    limits.memory: 192Gi
    requests.nvidia.com/gpu: "8"
    pods: "80"
    services: "20"
    persistentvolumeclaims: "16"
