{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: {name: regulated-ai-api}
spec:
  podSelector:
    matchLabels: {app: regulated-ai-api}
  policyTypes: ["Ingress", "Egress"]
  ingress:
    - ports: [{protocol: TCP, port: 8000}]
  egress:
    - ports: [{protocol: UDP, port: 53}, {protocol: TCP, port: 53}]
{{- if and .Values.registryRuntime.enabled .Values.networkPolicy.mlflowEgress.enabled }}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.mlflowEgress.namespace | quote }}
          podSelector:
            matchLabels:
              app: {{ .Values.networkPolicy.mlflowEgress.podLabel | quote }}
      ports:
        - {protocol: TCP, port: {{ .Values.networkPolicy.mlflowEgress.port }}}
{{- end }}
{{- end }}
