apiVersion: v1
kind: Service
metadata: {name: regulated-ai-api}
spec:
  type: {{ .Values.service.type }}
  selector: {app: regulated-ai-api}
  ports:
    - {name: http, port: {{ .Values.service.port }}, targetPort: http}
