#!/usr/bin/env python3
"""Fail closed when release versions or generated evidence disagree.

The repository keeps human-readable evidence snapshots for orientation, but the
release workflow publishes only artifacts generated by the validated Platform
workflow run.  This checker protects both boundaries:

* source mode checks every platform/service deployment surface against VERSION;
* artifact mode checks that one CI run produced a coherent, releasable evidence
  set for the expected version and Git commit.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SEMVER = re.compile(r"[0-9]+\.[0-9]+\.[0-9]+")
FULL_SHA = re.compile(r"[0-9a-f]{40}")


class ConsistencyError(RuntimeError):
    """Raised when a release input cannot be proved internally consistent."""


def _read(path: Path) -> str:
    if not path.is_file():
        raise ConsistencyError(f"required file is missing: {path}")
    return path.read_text(encoding="utf-8")


def _json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(_read(path))
    except json.JSONDecodeError as exc:
        raise ConsistencyError(f"invalid JSON in {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise ConsistencyError(f"expected a JSON object in {path}")
    return value


def _matches(root: Path, relative: str, pattern: str, expected_count: int) -> list[str]:
    values = re.findall(pattern, _read(root / relative), flags=re.MULTILINE)
    if len(values) != expected_count:
        raise ConsistencyError(
            f"{relative}: expected {expected_count} match(es) for {pattern!r}, found {len(values)}"
        )
    return values


def check_source_consistency(root: Path = ROOT) -> str:
    """Return the release version after validating all source declarations."""

    version = _read(root / "VERSION").strip()
    if SEMVER.fullmatch(version) is None:
        raise ConsistencyError(f"VERSION must contain one stable semantic version, found {version!r}")

    declarations: list[tuple[str, str]] = []
    rules = [
        ("pyproject.toml", r'^version = "([^"]+)"$', 1),
        ("src/core/config.py", r'service_version: str = os\.getenv\("SERVICE_VERSION", "([^"]+)"\)', 1),
        ("docker/Dockerfile", r'org\.opencontainers\.image\.version="([^"]+)"', 1),
        ("docker/Dockerfile", r"\bSERVICE_VERSION=([^\s]+)", 1),
        ("docker-compose.yml", r"regulated-ai-mlops-platform:([^\s]+)", 1),
        ("docker-compose.yml", r'SERVICE_VERSION: "([^"]+)"', 1),
        ("k8s/deployment.yaml", r'app\.kubernetes\.io/version: "([^"]+)"', 2),
        ("k8s/deployment.yaml", r"ghcr\.io/xm2325/regulated_ml_platform:([^\s]+)", 1),
        ("k8s/deployment.yaml", r'^\s+value: "([0-9]+\.[0-9]+\.[0-9]+)"$', 1),
        ("helm/regulated-ai/Chart.yaml", r"^version: ([^\s]+)$", 1),
        ("helm/regulated-ai/Chart.yaml", r'^appVersion: "([^"]+)"$', 1),
        ("helm/regulated-ai/values.yaml", r'^\s+tag: "([^"]+)"$', 1),
    ]
    for relative, pattern, count in rules:
        declarations.extend((relative, value) for value in _matches(root, relative, pattern, count))

    mismatches = [f"{relative}={value}" for relative, value in declarations if value != version]
    if mismatches:
        raise ConsistencyError(
            f"platform/service declarations must equal VERSION {version}: " + ", ".join(mismatches)
        )

    makefile = _read(root / "Makefile")
    required_make_fragments = (
        "PLATFORM_VERSION := $(strip $(shell cat VERSION))",
        "regulated-ai-mlops-platform:$(PLATFORM_VERSION)",
        "--model-version $(MODEL_VERSION)",
        "release-consistency:",
    )
    missing_make = [fragment for fragment in required_make_fragments if fragment not in makefile]
    if missing_make:
        raise ConsistencyError(f"Makefile does not use VERSION consistently: {missing_make}")

    release_workflow = _read(root / ".github/workflows/release.yml")
    required_release_fragments = (
        '"service-${RELEASE_VERSION}"',
        '"platform-${RELEASE_VERSION}"',
        "python scripts/check_release_consistency.py",
        ".name == \"Platform build, test, container, and evidence\"",
    )
    missing_release = [fragment for fragment in required_release_fragments if fragment not in release_workflow]
    if missing_release:
        raise ConsistencyError(f"release workflow is missing consistency controls: {missing_release}")
    if re.search(r'"(?:service|platform)-[0-9]+\.[0-9]+\.[0-9]+"', release_workflow):
        raise ConsistencyError("release workflow must derive service/platform tags from VERSION")

    platform_workflow = _read(root / ".github/workflows/platform.yml")
    required_platform_fragments = (
        "SOURCE_SHA: ${{ github.event.pull_request.head.sha || github.sha }}",
        "IMAGE_TAG: ${{ github.event.pull_request.head.sha || github.sha }}",
        "ref: ${{ env.SOURCE_SHA }}",
        "release-evidence-consistency:",
        '--source-sha "${SOURCE_SHA}"',
        "needs: release-evidence-consistency",
    )
    missing_platform = [
        fragment for fragment in required_platform_fragments if fragment not in platform_workflow
    ]
    if missing_platform:
        raise ConsistencyError(
            "Platform workflow must check out and tag the real source SHA: "
            + ", ".join(missing_platform)
        )

    preprod_overlay = _read(root / "gitops/environments/preprod/kustomization.yaml")
    prod_overlay = _read(root / "gitops/environments/prod/kustomization.yaml")
    for label, overlay in (("preprod", preprod_overlay), ("production", prod_overlay)):
        if "../../gpu" in overlay or "regulated_ml_platform-triton" in overlay:
            raise ConsistencyError(
                f"{label} must not activate the Triton contract before its image/model release path exists"
            )
    prod_digests = re.findall(r"^\s+digest: (sha256:[0-9a-f]{64})$", prod_overlay, flags=re.MULTILINE)
    if len(prod_digests) != 1 or "newTag:" in prod_overlay:
        raise ConsistencyError("production must declare one API image by immutable SHA-256 digest only")

    sbom_source = _read(root / "src/operations/generate_sbom.py")
    if '"version": "0.6.0"' in sbom_source or 'ROOT / "VERSION"' not in sbom_source:
        raise ConsistencyError("SBOM application version must be derived from VERSION")

    readme = _read(root / "README.md")
    if f"Platform/service release: `{version}`" not in readme:
        raise ConsistencyError("README must identify the current platform/service release from VERSION")
    if "committed evidence snapshot" not in readme.lower() or "CI-generated release artifact" not in readme:
        raise ConsistencyError("README must distinguish the committed evidence snapshot from CI-generated artifacts")
    if re.search(r"\|\s*Automated tests\s*\|\s*[0-9]+\s+passed\s*\|", readme, flags=re.IGNORECASE):
        raise ConsistencyError("README must not hard-code a test count")

    return version


def _require_equal(label: str, value: Any, expected: str, errors: list[str]) -> None:
    if value != expected:
        errors.append(f"{label}: expected {expected!r}, found {value!r}")


def check_generated_artifacts(
    *,
    version: str,
    source_sha: str,
    model_dir: Path,
    evidence_dir: Path,
    site_dir: Path,
) -> None:
    """Validate artifacts downloaded from one successful Platform workflow run."""

    if FULL_SHA.fullmatch(source_sha) is None:
        raise ConsistencyError(f"source SHA must be 40 lowercase hexadecimal characters, found {source_sha!r}")

    metadata = _json(model_dir / "metadata.json")
    contract = _json(model_dir / "model_contract.json")
    metrics = _json(evidence_dir / "reports/model_metrics.json")
    gate = _json(evidence_dir / "reports/promotion_gate.json")
    approval = _json(evidence_dir / "reports/release_approval_pack.json")
    sbom = _json(evidence_dir / "reports/sbom.cdx.json")
    site = _json(site_dir / "data/evidence.json")

    errors: list[str] = []
    for label, value in (
        ("model metadata version", metadata.get("model_version")),
        ("model contract version", contract.get("model_version")),
        ("model metrics version", metrics.get("model_version")),
        ("metrics metadata version", metrics.get("metadata", {}).get("model_version")),
        ("release approval version", approval.get("model_version")),
        ("SBOM application version", sbom.get("metadata", {}).get("component", {}).get("version")),
        ("site evidence version", site.get("model_version")),
    ):
        _require_equal(label, value, version, errors)

    git_commit = metadata.get("git_commit")
    if not isinstance(git_commit, str) or not re.fullmatch(r"[0-9a-f]{7,40}", git_commit):
        errors.append(f"model metadata git_commit is not a usable SHA: {git_commit!r}")
    elif not source_sha.startswith(git_commit):
        errors.append(f"model metadata commit {git_commit!r} is not the release source {source_sha!r}")

    _require_equal("promotion gate", gate.get("status"), "PASS", errors)
    _require_equal("release approval", approval.get("overall_status"), "PASS", errors)
    _require_equal("site release status", site.get("release_status"), "PASS", errors)
    _require_equal(
        "approval promotion control",
        approval.get("control_statuses", {}).get("promotion"),
        "PASS",
        errors,
    )

    best_model = metrics.get("best_model")
    if not isinstance(best_model, str) or best_model not in metrics.get("models", {}):
        errors.append(f"best_model {best_model!r} has no matching metrics")

    for field in ("policy_version", "feature_schema_version"):
        expected = metadata.get(field)
        _require_equal(f"contract {field}", contract.get(field), expected, errors)
        _require_equal(f"metrics {field}", metrics.get("metadata", {}).get(field), expected, errors)

    trained_at = metrics.get("trained_at")
    if trained_at != metadata.get("created_at"):
        errors.append("model metrics and metadata do not identify the same training event")

    required_evidence = (
        "reports/model_evaluation.md",
        "reports/calibration_report.md",
        "reports/fairness_report.md",
        "reports/deployment_validation.md",
        "reports/reproducibility_manifest.json",
        "reports/sbom.cdx.json",
        "docs/model_contract.md",
        "docs/release_approval_pack.md",
        "docs/reproducibility_manifest.md",
    )
    for relative in required_evidence:
        path = evidence_dir / relative
        if not path.is_file() or path.stat().st_size == 0:
            errors.append(f"required generated evidence is missing or empty: {relative}")

    for relative in ("docs/model_contract.md", "docs/release_approval_pack.md"):
        path = evidence_dir / relative
        if path.is_file() and version not in path.read_text(encoding="utf-8"):
            errors.append(f"{relative} does not identify model version {version}")

    index = site_dir / "index.html"
    if not index.is_file() or index.stat().st_size == 0:
        errors.append("generated site/index.html is missing or empty")
    elif f"Version {version}" not in index.read_text(encoding="utf-8"):
        errors.append(f"generated site does not identify model version {version}")

    if errors:
        raise ConsistencyError("generated release evidence is inconsistent:\n- " + "\n- ".join(errors))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--source-sha")
    parser.add_argument("--model-dir", type=Path)
    parser.add_argument("--evidence-dir", type=Path)
    parser.add_argument("--site-dir", type=Path)
    args = parser.parse_args()

    version = check_source_consistency(args.root)
    artifact_args = (args.source_sha, args.model_dir, args.evidence_dir, args.site_dir)
    if any(value is not None for value in artifact_args):
        if not all(value is not None for value in artifact_args):
            parser.error("--source-sha, --model-dir, --evidence-dir, and --site-dir must be provided together")
        check_generated_artifacts(
            version=version,
            source_sha=args.source_sha,
            model_dir=args.model_dir,
            evidence_dir=args.evidence_dir,
            site_dir=args.site_dir,
        )
        print(f"release source and CI evidence are consistent for {version} at {args.source_sha}")
    else:
        print(f"platform/service release declarations are consistent at {version}")


if __name__ == "__main__":
    main()
